// Auto-generated by BuildVersionGenerator
namespace Tartaria.Core
{
    public static class BuildInfo
    {
        public const string Version = "v1.0.0-230-g379d8bf-dirty";
        public const string Hash = "379d8bf";
        public const string BuildTime = "2026-05-22 06:44:40 UTC";
    }
}
