// Auto-generated by BuildVersionGenerator
namespace Tartaria.Core
{
    public static class BuildInfo
    {
        public const string Version = "v1.0.0-123-gf95caec-dirty";
        public const string Hash = "f95caec";
        public const string BuildTime = "2026-05-13 13:38:36 UTC";
    }
}
