#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace Tartaria.Editor
{
    /// <summary>
    /// Moon1HeroBuildingMeshReplace — Sprint 11 L3 (P5.L3) hero-building mesh fix.
    ///
    /// Per Sprint 11 L6 audit (6fe7ffef): the 3 Echohaven hero building prefabs at
    ///   Assets/_Project/Prefabs/Moon1/Buildings/Echohaven_{CrystalSpire,StarDome,HarmonicFountain}.prefab
    /// each ship as ~60-88 Unity primitive Detail_* children (placeholder geometry generated by
    /// the legacy BuildingSpawner, commit 2e04e671). Not architecture — just procedural rings of
    /// cubes/cylinders. This tool rebuilds them from REAL meshes:
    ///
    ///   CrystalSpire   (~15m tall, narrow tower)
    ///       Foundation_16x16m
    ///       Wall_4x4m_Stone x 4 (cardinal walls of base tower)
    ///       Wall_Corner_4x4m x 4 (corners of base tower)
    ///       Spire_Base_2x2m
    ///       Spire_Mid_Taper
    ///       Spire_Top_MercuryBall
    ///
    ///   StarDome       (~18m tall, dome)
    ///       Foundation_16x16m
    ///       Wall_4x4m_Stone x 3 (S, E, W facades)
    ///       Wall_Corner_4x4m x 4
    ///       Door_Grand_3x6m (N facade entry)
    ///       Dome_Segment_{N,NE,E,SE,S,SW,W,NW} (full 8-segment dome ring)
    ///       RoseWindow_4x4m (above the door)
    ///       PipeOrganCathedral (interior centerpiece)
    ///
    ///   HarmonicFountain (~5m tall, low — heavily buried per docs/15 §7)
    ///       Foundation_16x16m
    ///       Wall_4x4m_Stone x 4 (low fountain perimeter)
    ///       Spire_Base_2x2m + Spire_Top_MercuryBall (central plinth + orb)
    ///
    /// Preserves the existing TuningNode_0/1/2, ParticleSystem, Light, BoxCollider components
    /// already present at the prefab root — only the visual child hierarchy is rebuilt.
    ///
    /// Idempotent: re-running clears any prior "HeroMesh_Kit" parent and rebuilds.
    ///
    /// Menu: Tartaria/1 Build/Replace Hero Building Detail_* Primitives With Kit Meshes
    /// </summary>
    public static class Moon1HeroBuildingMeshReplace
    {
        // ── Prefab paths ─────────────────────────────────────────────────────
        const string CrystalSpirePath    = "Assets/_Project/Prefabs/Moon1/Buildings/Echohaven_CrystalSpire.prefab";
        const string StarDomePath        = "Assets/_Project/Prefabs/Moon1/Buildings/Echohaven_StarDome.prefab";
        const string HarmonicFountainPath = "Assets/_Project/Prefabs/Moon1/Buildings/Echohaven_HarmonicFountain.prefab";

        const string KitRoot     = "Assets/_Project/Prefabs/Moon1/Cathedral/";
        const string BlenderRoot = "Assets/_Project/Prefabs/Moon1/Blender/";

        static readonly string PathFoundation = KitRoot + "Foundation_16x16m.prefab";
        static readonly string PathWallStone  = KitRoot + "Wall_4x4m_Stone.prefab";
        static readonly string PathWallCorner = KitRoot + "Wall_Corner_4x4m.prefab";
        static readonly string PathDoor       = KitRoot + "Door_Grand_3x6m.prefab";
        static readonly string PathRoseWindow = KitRoot + "RoseWindow_4x4m.prefab";
        static readonly string PathColumn     = KitRoot + "Column_Ornate_6.5m.prefab";
        static readonly string PathSpireBase  = KitRoot + "Spire_Base_2x2m.prefab";
        static readonly string PathSpireMid   = KitRoot + "Spire_Mid_Taper.prefab";
        static readonly string PathSpireTop   = KitRoot + "Spire_Top_MercuryBall.prefab";
        static readonly string PathPipeOrgan  = BlenderRoot + "PipeOrganCathedral.prefab";

        static readonly string[] DomeSegmentNames =
        {
            "Dome_Segment_N", "Dome_Segment_NE", "Dome_Segment_E", "Dome_Segment_SE",
            "Dome_Segment_S", "Dome_Segment_SW", "Dome_Segment_W", "Dome_Segment_NW"
        };

        const string KitParentName = "HeroMesh_Kit";

        // ── Menu ─────────────────────────────────────────────────────────────
        [MenuItem("Tartaria/1 Build/Replace Hero Building Detail_* Primitives With Kit Meshes", priority = 108)]
        public static void Run()
        {
            // Verify every source prefab exists before mutating anything.
            var required = new List<string>
            {
                CrystalSpirePath, StarDomePath, HarmonicFountainPath,
                PathFoundation, PathWallStone, PathWallCorner, PathDoor, PathRoseWindow,
                PathColumn, PathSpireBase, PathSpireMid, PathSpireTop, PathPipeOrgan
            };
            foreach (var n in DomeSegmentNames)
                required.Add(KitRoot + n + ".prefab");

            var missing = new List<string>();
            foreach (var p in required)
            {
                if (!File.Exists(p)) missing.Add(p);
            }
            if (missing.Count > 0)
            {
                EditorUtility.DisplayDialog(
                    "Hero Building Mesh Replace",
                    "Aborting — missing source prefabs:\n\n" + string.Join("\n", missing),
                    "OK");
                Debug.LogError("[Moon1HeroBuildingMeshReplace] Missing prefabs: " + string.Join(", ", missing));
                return;
            }

            int before, after;
            int totalBefore = 0, totalAfter = 0;

            ReplaceCrystalSpire(out before, out after);
            Debug.Log($"[Moon1HeroBuildingMeshReplace] CrystalSpire: {before} primitive Detail_* before -> {after} real kit children after.");
            totalBefore += before; totalAfter += after;

            ReplaceStarDome(out before, out after);
            Debug.Log($"[Moon1HeroBuildingMeshReplace] StarDome: {before} primitive Detail_* before -> {after} real kit children after.");
            totalBefore += before; totalAfter += after;

            ReplaceHarmonicFountain(out before, out after);
            Debug.Log($"[Moon1HeroBuildingMeshReplace] HarmonicFountain: {before} primitive Detail_* before -> {after} real kit children after.");
            totalBefore += before; totalAfter += after;

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            EditorUtility.DisplayDialog(
                "Hero Building Mesh Replace — DONE",
                $"Replaced {totalBefore} primitive Detail_* placeholder children\n" +
                $"with {totalAfter} real Cathedral kit + Blender FBX pieces\n" +
                $"across 3 hero prefabs.\n\n" +
                "TuningNode_0/1/2, ParticleSystem, Light, BoxCollider preserved.",
                "OK");
        }

        // ── CrystalSpire ─────────────────────────────────────────────────────
        // Tower: 4x4 foundation, low walled base, then Spire stack culminating in MercuryBall.
        static void ReplaceCrystalSpire(out int detailBefore, out int kitAfter)
        {
            var root = PrefabUtility.LoadPrefabContents(CrystalSpirePath);
            detailBefore = CountAndRemoveDetails(root, out _);

            var kit = NewKitParent(root);
            kitAfter = 0;

            // Foundation flush with prefab origin.
            InstantiateKitChild(PathFoundation,
                new Vector3(0f, 0f, 0f),
                Quaternion.identity, Vector3.one, kit.transform, ref kitAfter);

            // Low walled base (4 walls + 4 corners) at ground level for the spire tower base.
            // Walls placed on cardinal axes 4m out from origin.
            InstantiateKitChild(PathWallStone, new Vector3(0f, 0f, 4f),
                Quaternion.Euler(0f, 0f, 0f), Vector3.one, kit.transform, ref kitAfter);
            InstantiateKitChild(PathWallStone, new Vector3(4f, 0f, 0f),
                Quaternion.Euler(0f, 90f, 0f), Vector3.one, kit.transform, ref kitAfter);
            InstantiateKitChild(PathWallStone, new Vector3(0f, 0f, -4f),
                Quaternion.Euler(0f, 180f, 0f), Vector3.one, kit.transform, ref kitAfter);
            InstantiateKitChild(PathWallStone, new Vector3(-4f, 0f, 0f),
                Quaternion.Euler(0f, 270f, 0f), Vector3.one, kit.transform, ref kitAfter);

            InstantiateKitChild(PathWallCorner, new Vector3(4f, 0f, 4f),
                Quaternion.Euler(0f, 0f, 0f), Vector3.one, kit.transform, ref kitAfter);
            InstantiateKitChild(PathWallCorner, new Vector3(4f, 0f, -4f),
                Quaternion.Euler(0f, 90f, 0f), Vector3.one, kit.transform, ref kitAfter);
            InstantiateKitChild(PathWallCorner, new Vector3(-4f, 0f, -4f),
                Quaternion.Euler(0f, 180f, 0f), Vector3.one, kit.transform, ref kitAfter);
            InstantiateKitChild(PathWallCorner, new Vector3(-4f, 0f, 4f),
                Quaternion.Euler(0f, 270f, 0f), Vector3.one, kit.transform, ref kitAfter);

            // Spire stack — Spire_Base (4m tall) sits on top of the 4m walls,
            // Spire_Mid_Taper (~5m tall) above that, Spire_Top_MercuryBall finial above that.
            InstantiateKitChild(PathSpireBase, new Vector3(0f, 4f, 0f),
                Quaternion.identity, Vector3.one, kit.transform, ref kitAfter);
            InstantiateKitChild(PathSpireMid, new Vector3(0f, 8f, 0f),
                Quaternion.identity, Vector3.one, kit.transform, ref kitAfter);
            InstantiateKitChild(PathSpireTop, new Vector3(0f, 13f, 0f),
                Quaternion.identity, Vector3.one, kit.transform, ref kitAfter);

            PrefabUtility.SaveAsPrefabAsset(root, CrystalSpirePath);
            PrefabUtility.UnloadPrefabContents(root);
        }

        // ── StarDome ─────────────────────────────────────────────────────────
        // Big domed rotunda: foundation + 4 corner stones + 3 walls + grand door (N)
        // + full 8-segment dome on top + rose window above door + central pipe organ.
        static void ReplaceStarDome(out int detailBefore, out int kitAfter)
        {
            var root = PrefabUtility.LoadPrefabContents(StarDomePath);
            detailBefore = CountAndRemoveDetails(root, out _);

            var kit = NewKitParent(root);
            kitAfter = 0;

            // Foundation at origin.
            InstantiateKitChild(PathFoundation,
                new Vector3(0f, 0f, 0f),
                Quaternion.identity, Vector3.one, kit.transform, ref kitAfter);

            // 4 wall corners 4m out on diagonals.
            InstantiateKitChild(PathWallCorner, new Vector3(4f, 0f, 4f),
                Quaternion.Euler(0f, 0f, 0f), Vector3.one, kit.transform, ref kitAfter);
            InstantiateKitChild(PathWallCorner, new Vector3(4f, 0f, -4f),
                Quaternion.Euler(0f, 90f, 0f), Vector3.one, kit.transform, ref kitAfter);
            InstantiateKitChild(PathWallCorner, new Vector3(-4f, 0f, -4f),
                Quaternion.Euler(0f, 180f, 0f), Vector3.one, kit.transform, ref kitAfter);
            InstantiateKitChild(PathWallCorner, new Vector3(-4f, 0f, 4f),
                Quaternion.Euler(0f, 270f, 0f), Vector3.one, kit.transform, ref kitAfter);

            // 3 stone wall facades + grand door (N entry).
            // N facade -> Door_Grand_3x6m at z=+4 facing +Z
            InstantiateKitChild(PathDoor, new Vector3(0f, 0f, 4f),
                Quaternion.Euler(0f, 0f, 0f), Vector3.one, kit.transform, ref kitAfter);
            // E facade -> Wall_4x4m_Stone at x=+4 facing +X
            InstantiateKitChild(PathWallStone, new Vector3(4f, 0f, 0f),
                Quaternion.Euler(0f, 90f, 0f), Vector3.one, kit.transform, ref kitAfter);
            // S facade
            InstantiateKitChild(PathWallStone, new Vector3(0f, 0f, -4f),
                Quaternion.Euler(0f, 180f, 0f), Vector3.one, kit.transform, ref kitAfter);
            // W facade
            InstantiateKitChild(PathWallStone, new Vector3(-4f, 0f, 0f),
                Quaternion.Euler(0f, 270f, 0f), Vector3.one, kit.transform, ref kitAfter);

            // Rose window above the door.
            InstantiateKitChild(PathRoseWindow, new Vector3(0f, 4.5f, 4f),
                Quaternion.identity, Vector3.one, kit.transform, ref kitAfter);

            // 8-segment dome, ring of 8 around top of walls (~y=4m up, on a 4m-radius circle).
            const float DomeRingRadius = 4f;
            const float DomeRingHeight = 4.5f;
            for (int i = 0; i < DomeSegmentNames.Length; i++)
            {
                float angleDeg = i * 45f; // N=0, NE=45, E=90, ...
                float rad = Mathf.Deg2Rad * angleDeg;
                Vector3 pos = new Vector3(
                    Mathf.Sin(rad) * DomeRingRadius,
                    DomeRingHeight,
                    Mathf.Cos(rad) * DomeRingRadius);
                Quaternion rot = Quaternion.Euler(0f, angleDeg, 0f);
                InstantiateKitChild(KitRoot + DomeSegmentNames[i] + ".prefab",
                    pos, rot, Vector3.one, kit.transform, ref kitAfter);
            }

            // Centerpiece: pipe organ inside the dome.
            InstantiateKitChild(PathPipeOrgan, new Vector3(0f, 0f, 0f),
                Quaternion.identity, Vector3.one, kit.transform, ref kitAfter);

            PrefabUtility.SaveAsPrefabAsset(root, StarDomePath);
            PrefabUtility.UnloadPrefabContents(root);
        }

        // ── HarmonicFountain ─────────────────────────────────────────────────
        // Low fountain plinth: foundation + 4 short walls (rim) + central spire base + mercury orb.
        // Building is heavily buried per docs/15 §7 — only ~0.25m visible at start of game.
        // We build the FULL structure here; sinking is handled by Moon1BuildOutBuildings.cs.
        static void ReplaceHarmonicFountain(out int detailBefore, out int kitAfter)
        {
            var root = PrefabUtility.LoadPrefabContents(HarmonicFountainPath);
            detailBefore = CountAndRemoveDetails(root, out _);

            var kit = NewKitParent(root);
            kitAfter = 0;

            // Foundation.
            InstantiateKitChild(PathFoundation,
                new Vector3(0f, 0f, 0f),
                Quaternion.identity, Vector3.one, kit.transform, ref kitAfter);

            // 4 short walls as rim — scaled vertically to half height so it reads as a fountain basin.
            Vector3 rimScale = new Vector3(1f, 0.5f, 1f);
            InstantiateKitChild(PathWallStone, new Vector3(0f, 0f, 4f),
                Quaternion.Euler(0f, 0f, 0f), rimScale, kit.transform, ref kitAfter);
            InstantiateKitChild(PathWallStone, new Vector3(4f, 0f, 0f),
                Quaternion.Euler(0f, 90f, 0f), rimScale, kit.transform, ref kitAfter);
            InstantiateKitChild(PathWallStone, new Vector3(0f, 0f, -4f),
                Quaternion.Euler(0f, 180f, 0f), rimScale, kit.transform, ref kitAfter);
            InstantiateKitChild(PathWallStone, new Vector3(-4f, 0f, 0f),
                Quaternion.Euler(0f, 270f, 0f), rimScale, kit.transform, ref kitAfter);

            // 4 corner posts (also half height).
            InstantiateKitChild(PathWallCorner, new Vector3(4f, 0f, 4f),
                Quaternion.Euler(0f, 0f, 0f), rimScale, kit.transform, ref kitAfter);
            InstantiateKitChild(PathWallCorner, new Vector3(4f, 0f, -4f),
                Quaternion.Euler(0f, 90f, 0f), rimScale, kit.transform, ref kitAfter);
            InstantiateKitChild(PathWallCorner, new Vector3(-4f, 0f, -4f),
                Quaternion.Euler(0f, 180f, 0f), rimScale, kit.transform, ref kitAfter);
            InstantiateKitChild(PathWallCorner, new Vector3(-4f, 0f, 4f),
                Quaternion.Euler(0f, 270f, 0f), rimScale, kit.transform, ref kitAfter);

            // Central plinth + mercury orb finial.
            InstantiateKitChild(PathSpireBase, new Vector3(0f, 0f, 0f),
                Quaternion.identity, Vector3.one, kit.transform, ref kitAfter);
            InstantiateKitChild(PathSpireTop, new Vector3(0f, 3f, 0f),
                Quaternion.identity, Vector3.one, kit.transform, ref kitAfter);

            PrefabUtility.SaveAsPrefabAsset(root, HarmonicFountainPath);
            PrefabUtility.UnloadPrefabContents(root);
        }

        // ── Helpers ──────────────────────────────────────────────────────────

        /// <summary>
        /// Removes every immediate child whose name starts with "Detail_" plus
        /// any prior "HeroMesh_Kit" parent (idempotency). Returns the count of
        /// Detail_* children that existed before the strip.
        /// </summary>
        static int CountAndRemoveDetails(GameObject root, out int detailsKept)
        {
            detailsKept = 0;
            int removed = 0;
            // Walk children in reverse — DestroyImmediate during enumeration is unsafe otherwise.
            for (int i = root.transform.childCount - 1; i >= 0; i--)
            {
                var child = root.transform.GetChild(i).gameObject;
                if (child.name.StartsWith("Detail_"))
                {
                    Object.DestroyImmediate(child, true);
                    removed++;
                }
                else if (child.name == KitParentName)
                {
                    // Existing kit parent from a previous run -> wipe for clean rebuild.
                    Object.DestroyImmediate(child, true);
                }
                else
                {
                    detailsKept++;
                }
            }
            return removed;
        }

        static GameObject NewKitParent(GameObject root)
        {
            var go = new GameObject(KitParentName);
            go.transform.SetParent(root.transform, false);
            go.transform.localPosition = Vector3.zero;
            go.transform.localRotation = Quaternion.identity;
            go.transform.localScale = Vector3.one;
            return go;
        }

        static void InstantiateKitChild(
            string prefabPath,
            Vector3 localPos,
            Quaternion localRot,
            Vector3 localScale,
            Transform parent,
            ref int counter)
        {
            var src = AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath);
            if (src == null)
            {
                Debug.LogError($"[Moon1HeroBuildingMeshReplace] Source prefab missing: {prefabPath}");
                return;
            }
            var inst = (GameObject)PrefabUtility.InstantiatePrefab(src, parent);
            if (inst == null)
            {
                Debug.LogError($"[Moon1HeroBuildingMeshReplace] Failed to instantiate: {prefabPath}");
                return;
            }
            inst.transform.localPosition = localPos;
            inst.transform.localRotation = localRot;
            inst.transform.localScale = localScale;
            counter++;
        }
    }
}
#endif
