using UnityEditor;
using UnityEngine;
using System.IO;

namespace Tartaria.Editor
{
    /// <summary>
    /// BuildVersionGenerator: reads `git describe --tags --always --dirty`
    /// and writes Assets/_Project/Scripts/Core/BuildInfo.cs with version + hash.
    /// 
    /// Run from menu: Tartaria → Generate Build Version
    /// Also called automatically by OneClickBuild before each build.
    /// </summary>
    public static class BuildVersionGenerator
    {
        const string OUTPUT_PATH = "Assets/_Project/Scripts/Core/BuildInfo.cs";

        [MenuItem("Tartaria/Generate Build Version", priority = 105)]
        public static void Generate()
        {
            string version = GetGitVersion();
            string hash = GetGitHash();
            string buildTime = System.DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss UTC");

            string content = $@"// Auto-generated by BuildVersionGenerator
namespace Tartaria.Core
{{
    public static class BuildInfo
    {{
        public const string Version = ""{version}"";
        public const string Hash = ""{hash}"";
        public const string BuildTime = ""{buildTime}"";
    }}
}}
";

            Directory.CreateDirectory(Path.GetDirectoryName(OUTPUT_PATH));
            File.WriteAllText(OUTPUT_PATH, content);
            AssetDatabase.Refresh();

            Debug.Log($"[BuildVersion] Generated: {version} ({hash}) at {buildTime}");
        }

        static string GetGitVersion()
        {
            try
            {
                var proc = new System.Diagnostics.Process
                {
                    StartInfo = new System.Diagnostics.ProcessStartInfo
                    {
                        FileName = "git",
                        Arguments = "describe --tags --always --dirty",
                        UseShellExecute = false,
                        RedirectStandardOutput = true,
                        CreateNoWindow = true,
                        WorkingDirectory = Application.dataPath.Replace("/Assets", "")
                    }
                };
                proc.Start();
                string output = proc.StandardOutput.ReadToEnd().Trim();
                proc.WaitForExit();
                return string.IsNullOrEmpty(output) ? "unknown" : output;
            }
            catch
            {
                return "unknown";
            }
        }

        static string GetGitHash()
        {
            try
            {
                var proc = new System.Diagnostics.Process
                {
                    StartInfo = new System.Diagnostics.ProcessStartInfo
                    {
                        FileName = "git",
                        Arguments = "rev-parse --short HEAD",
                        UseShellExecute = false,
                        RedirectStandardOutput = true,
                        CreateNoWindow = true,
                        WorkingDirectory = Application.dataPath.Replace("/Assets", "")
                    }
                };
                proc.Start();
                string output = proc.StandardOutput.ReadToEnd().Trim();
                proc.WaitForExit();
                return string.IsNullOrEmpty(output) ? "unknown" : output;
            }
            catch
            {
                return "unknown";
            }
        }
    }
}
