using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text.RegularExpressions;

namespace Tartaria.Editor.AssetGen
{
    /// <summary>
    /// Generates prefab loader utility class that spawner scripts can use
    /// to instantiate production prefabs instead of primitives.
    /// </summary>
    public class PrefabWireupGenerator : EditorWindow
    {
        const string OUTPUT_PATH = "Assets/_Project/Scripts/Integration/PrefabLibrary.cs";
        const string PREFABS_CHARACTERS = "Assets/_Project/Prefabs/Characters";
        const string PREFABS_STRUCTURES = "Assets/_Project/Prefabs/Buildings";
        const string PREFABS_VFX = "Assets/_Project/Prefabs/VFX";

        [MenuItem("Tartaria/Asset Replacement/Generate Prefab Library")]
        public static void GeneratePrefabLibrary()
        {
            string code = GeneratePrefabLibraryCode();
            File.WriteAllText(OUTPUT_PATH, code);
            AssetDatabase.Refresh();

            Debug.Log($"[PrefabWireupGenerator] ✓ Generated prefab library: {OUTPUT_PATH}");
            Debug.Log("[PrefabWireupGenerator] Now update spawner scripts to use PrefabLibrary.LoadCharacter() instead of GameObject.CreatePrimitive()");
        }

        static string GeneratePrefabLibraryCode()
        {
            return @"using UnityEngine;

namespace Tartaria.Integration
{
    /// <summary>
    /// Central prefab loader for all production assets.
    /// Replaces GameObject.CreatePrimitive() calls with proper prefab instantiation.
    /// Auto-generated by PrefabWireupGenerator.
    /// </summary>
    public static class PrefabLibrary
    {
        // Prefab paths
        const string CHARACTERS = ""Assets/_Project/Prefabs/Characters"";
        const string STRUCTURES = ""Assets/_Project/Prefabs/Buildings"";
        const string VFX = ""Assets/_Project/Prefabs/VFX"";

        #region Character Loading

        public static GameObject LoadCharacter(string characterName)
        {
            string path = $""{CHARACTERS}/{characterName}"";
            GameObject prefab = Resources.Load<GameObject>(path);
            
            if (prefab == null)
            {
                // Fallback to Resources folder if not found in Prefabs
                prefab = Resources.Load<GameObject>($""Prefabs/Characters/{characterName}"");
            }

            if (prefab == null)
            {
                Debug.LogWarning($""[PrefabLibrary] Character prefab not found: {characterName}. Using capsule fallback."");
                return GameObject.CreatePrimitive(PrimitiveType.Capsule);
            }

            return Object.Instantiate(prefab);
        }

        public static GameObject LoadMilo() => LoadCharacter(""Milo"");
        public static GameObject LoadAnastasia() => LoadCharacter(""Anastasia"");
        public static GameObject LoadMudGolem() => LoadCharacter(""MudGolem"");
        public static GameObject LoadLirael() => LoadCharacter(""Lirael"");
        public static GameObject LoadKorath() => LoadCharacter(""Korath"");
        public static GameObject LoadCaptainThorne() => LoadCharacter(""CaptainThorne"");
        public static GameObject LoadCassian() => LoadCharacter(""Cassian"");

        #endregion

        #region Structure Loading

        public static GameObject LoadStructure(string structureName)
        {
            string path = $""{STRUCTURES}/{structureName}"";
            GameObject prefab = Resources.Load<GameObject>(path);

            if (prefab == null)
            {
                prefab = Resources.Load<GameObject>($""Prefabs/Buildings/{structureName}"");
            }

            if (prefab == null)
            {
                Debug.LogWarning($""[PrefabLibrary] Structure prefab not found: {structureName}. Using cube fallback."");
                return GameObject.CreatePrimitive(PrimitiveType.Cube);
            }

            return Object.Instantiate(prefab);
        }

        public static GameObject LoadRailwayStation() => LoadStructure(""RailwayStation"");
        public static GameObject LoadHarmonicFountain() => LoadStructure(""HarmonicFountain"");
        public static GameObject LoadBellTower() => LoadStructure(""BellTower"");
        public static GameObject LoadBeauxArtsPavilion() => LoadStructure(""BeauxArtsPavilion"");

        #endregion

        #region VFX Loading

        public static GameObject LoadVFX(string vfxName)
        {
            string path = $""{VFX}/{vfxName}"";
            GameObject prefab = Resources.Load<GameObject>(path);

            if (prefab == null)
            {
                prefab = Resources.Load<GameObject>($""Prefabs/VFX/{vfxName}"");
            }

            if (prefab == null)
            {
                Debug.LogWarning($""[PrefabLibrary] VFX prefab not found: {vfxName}."");
                return new GameObject($""{vfxName}_Missing"");
            }

            return Object.Instantiate(prefab);
        }

        public static GameObject LoadCathedralTransformation() => LoadVFX(""CathedralTransformation"");
        public static GameObject LoadGoldenRailsPermanence() => LoadVFX(""GoldenRailsPermanence"");
        public static GameObject LoadAuroraCityManifestation() => LoadVFX(""AuroraCityManifestation"");
        public static GameObject LoadCosmicConvergence() => LoadVFX(""CosmicConvergence"");

        #endregion

        #region Utilities

        /// <summary>
        /// Loads prefab from Resources folder by partial name match.
        /// </summary>
        public static GameObject LoadFromResources(string partialName, PrimitiveType fallback = PrimitiveType.Cube)
        {
            // Try exact match first
            GameObject prefab = Resources.Load<GameObject>(partialName);
            if (prefab != null) return Object.Instantiate(prefab);

            // Try in common folders
            string[] folders = { ""Prefabs/Characters"", ""Prefabs/Buildings"", ""Prefabs/VFX"", ""Prefabs/Props"" };
            foreach (string folder in folders)
            {
                prefab = Resources.Load<GameObject>($""{folder}/{partialName}"");
                if (prefab != null) return Object.Instantiate(prefab);
            }

            Debug.LogWarning($""[PrefabLibrary] Could not find prefab: {partialName}. Using primitive fallback."");
            return GameObject.CreatePrimitive(fallback);
        }

        #endregion
    }
}
";
        }

        [MenuItem("Tartaria/Asset Replacement/Preview Spawner Updates")]
        public static void PreviewSpawnerUpdates()
        {
            Debug.Log("[PrefabWireupGenerator] === Spawner Update Preview ===");
            Debug.Log("\nMoon7ContentSpawner.cs changes:");
            Debug.Log("  Line 151: GameObject.CreatePrimitive(PrimitiveType.Capsule)");
            Debug.Log("       → GameObject korath = PrefabLibrary.LoadKorath();");
            Debug.Log("\n  Line 194: GameObject.CreatePrimitive(PrimitiveType.Capsule)");
            Debug.Log("       → GameObject cassian = PrefabLibrary.LoadCassian();");
            Debug.Log("\n  Line 250: GameObject.CreatePrimitive(PrimitiveType.Capsule)");
            Debug.Log("       → GameObject golem = PrefabLibrary.LoadMudGolem();");

            Debug.Log("\nMoon10ContentSpawner.cs changes:");
            Debug.Log("  Line 109: GameObject.CreatePrimitive(PrimitiveType.Cube)");
            Debug.Log("       → GameObject building = PrefabLibrary.LoadRailwayStation();");

            Debug.Log("\nBuildingSpawner.cs changes:");
            Debug.Log("  Line 312: GameObject.CreatePrimitive(shape)");
            Debug.Log("       → GameObject building = PrefabLibrary.LoadStructure(structureType);");

            Debug.Log("\n[PrefabWireupGenerator] Run 'Tartaria/Asset Replacement/Apply Spawner Updates' to make changes.");
        }

        [MenuItem("Tartaria/Asset Replacement/Apply Spawner Updates")]
        public static void ApplySpawnerUpdates()
        {
            Debug.Log("[PrefabWireupGenerator] Applying spawner updates...");

            // Update Moon7ContentSpawner
            UpdateMoon7ContentSpawner();

            // Update Moon10ContentSpawner
            UpdateMoon10ContentSpawner();

            // Update BuildingSpawner
            UpdateBuildingSpawner();

            AssetDatabase.Refresh();
            Debug.Log("[PrefabWireupGenerator] ✓ All spawner scripts updated to use PrefabLibrary!");
        }

        static void UpdateMoon7ContentSpawner()
        {
            string path = ""Assets/_Project/Scripts/Integration/Moon7ContentSpawner.cs"";
            if (!File.Exists(path))
            {
                Debug.LogWarning($""[PrefabWireupGenerator] File not found: {path}"");
                return;
            }

            string content = File.ReadAllText(path);

            // Add using directive if not present
            if (!content.Contains(""using Tartaria.Integration;""))
            {
                content = content.Replace(""using Tartaria.World;"", 
                    ""using Tartaria.World;\nusing Tartaria.Integration;"");
            }

            // Replace Korath giant spawn
            content = Regex.Replace(content,
                @"_korathGiant = GameObject\.CreatePrimitive\(PrimitiveType\.Capsule\);\s*\n\s*_korathGiant\.name = ""Korath_Giant"";\s*\n\s*_korathGiant\.transform\.position = .*;",
                @"_korathGiant = PrefabLibrary.LoadKorath();
            _korathGiant.name = ""Korath_Giant"";
            _korathGiant.transform.position = stasisVaultCenter + Vector3.up * 5f;");

            // Replace Cassian spawn
            content = Regex.Replace(content,
                @"GameObject cassianObj = GameObject\.CreatePrimitive\(PrimitiveType\.Capsule\);",
                @"GameObject cassianObj = PrefabLibrary.LoadCassian();");

            // Replace mud golem spawn
            content = Regex.Replace(content,
                @"GameObject golemObj = GameObject\.CreatePrimitive\(PrimitiveType\.Capsule\);",
                @"GameObject golemObj = PrefabLibrary.LoadMudGolem();");

            File.WriteAllText(path, content);
            Debug.Log($""[PrefabWireupGenerator] ✓ Updated: {path}"");
        }

        static void UpdateMoon10ContentSpawner()
        {
            string path = ""Assets/_Project/Scripts/Integration/Moon10ContentSpawner.cs"";
            if (!File.Exists(path))
            {
                Debug.LogWarning($""[PrefabWireupGenerator] File not found: {path}"");
                return;
            }

            string content = File.ReadAllText(path);

            // Add using directive
            if (!content.Contains(""using Tartaria.Integration;""))
            {
                content = content.Replace(""using Tartaria.World;"", 
                    ""using Tartaria.World;\nusing Tartaria.Integration;"");
            }

            // Replace station building spawn
            content = Regex.Replace(content,
                @"var building = GameObject\.CreatePrimitive\(PrimitiveType\.Cube\);\s*\n\s*building\.name = ""StationBuilding"";\s*\n\s*building\.transform\.SetParent\(station\.transform\);\s*\n\s*building\.transform\.localScale = new Vector3\(30f, 10f, 30f\);",
                @"var building = PrefabLibrary.LoadRailwayStation();
            building.name = ""StationBuilding"";
            building.transform.SetParent(station.transform);");

            File.WriteAllText(path, content);
            Debug.Log($""[PrefabWireupGenerator] ✓ Updated: {path}"");
        }

        static void UpdateBuildingSpawner()
        {
            string path = ""Assets/_Project/Scripts/Integration/BuildingSpawner.cs"";
            if (!File.Exists(path))
            {
                Debug.LogWarning($""[PrefabWireupGenerator] File not found: {path}"");
                return;
            }

            string content = File.ReadAllText(path);

            // Add using directive
            if (!content.Contains(""using Tartaria.Integration;""))
            {
                content = content.Replace(""using Tartaria.World;"", 
                    ""using Tartaria.World;\nusing Tartaria.Integration;"");
            }

            // Add helper method to map building type to prefab
            string helperMethod = @"
        static GameObject LoadBuildingPrefab(string buildingType)
        {
            return buildingType switch
            {
                ""dome"" => PrefabLibrary.LoadBeauxArtsPavilion(),
                ""fountain"" => PrefabLibrary.LoadHarmonicFountain(),
                ""spire"" => PrefabLibrary.LoadBellTower(),
                _ => GameObject.CreatePrimitive(PrimitiveType.Cube)
            };
        }";

            // Insert helper method before LoadFallbackBuilding method
            if (!content.Contains(""LoadBuildingPrefab""))
            {
                content = content.Replace(
                    ""static GameObject LoadFallbackBuilding("",
                    helperMethod + ""\n\n        static GameObject LoadFallbackBuilding("");
            }

            // Replace primitive creation in LoadFallbackBuilding
            content = Regex.Replace(content,
                @"// Fallback: primitives\s*\n\s*var go = GameObject\.CreatePrimitive\(shape\);",
                @"// Try loading production prefab first
            var go = LoadBuildingPrefab(category);");

            File.WriteAllText(path, content);
            Debug.Log($""[PrefabWireupGenerator] ✓ Updated: {path}"");
        }
    }
}
