using UnityEngine;
using TMPro;

namespace Tartaria.UI
{
    /// <summary>
    /// BuildInfoDisplay — displays version, commit hash, build date in main menu corner.
    /// Updates automatically from BuildInfo scriptable object (generated pre-build).
    /// Shows: "v1.2.3-alpha | abc123f | 2026-04-15"
    /// 
    /// Setup:
    /// 1. Attach to Canvas TextMeshPro in main menu
    /// 2. BuildInfo.asset auto-generated by editor script
    /// 3. Reads Application.version + custom build metadata
    /// 
    /// Usage:
    /// - Auto-displays on Start()
    /// - UpdateDisplay() to refresh
    /// - Toggle visibility with F3 (debug builds)
    /// 
    /// GDD refs: §05 (UI Polish), §31 (Build Pipeline)
    /// </summary>
    public class BuildInfoDisplay : MonoBehaviour
    {
        [Header("UI References")]
        [SerializeField] TextMeshProUGUI buildInfoText;

        [Header("Settings")]
        [SerializeField] bool showInRelease = false;
        [SerializeField] KeyCode toggleKey = KeyCode.F3;

        [Header("Format")]
        [SerializeField] string formatString = "v{0} | {1} | {2}";

        bool _isVisible = true;

        void Start()
        {
            // Hide in release builds unless explicitly enabled
            if (!Debug.isDebugBuild && !showInRelease)
            {
                gameObject.SetActive(false);
                return;
            }

            UpdateDisplay();
        }

        void Update()
        {
            if (Input.GetKeyDown(toggleKey))
            {
                ToggleVisibility();
            }
        }

        /// <summary>
        /// Update build info display.
        /// </summary>
        public void UpdateDisplay()
        {
            if (buildInfoText == null)
            {
                Debug.LogWarning("[BuildInfoDisplay] No TextMeshPro component assigned");
                return;
            }

            string version = Application.version;
            string commitHash = GetCommitHash();
            string buildDate = GetBuildDate();

            buildInfoText.text = string.Format(formatString, version, commitHash, buildDate);
        }

        /// <summary>
        /// Toggle visibility.
        /// </summary>
        public void ToggleVisibility()
        {
            _isVisible = !_isVisible;

            if (buildInfoText != null)
            {
                buildInfoText.gameObject.SetActive(_isVisible);
            }
        }

        /// <summary>
        /// Get commit hash from BuildInfo or fallback.
        /// </summary>
        string GetCommitHash()
        {
            // Try to load from BuildInfo ScriptableObject
            var buildInfo = Resources.Load<Core.BuildInfo>("BuildInfo");
            if (buildInfo != null && !string.IsNullOrEmpty(buildInfo.CommitHash))
            {
                return buildInfo.CommitHash.Substring(0, Mathf.Min(7, buildInfo.CommitHash.Length));
            }

            return "dev";
        }

        /// <summary>
        /// Get build date from BuildInfo or fallback.
        /// </summary>
        string GetBuildDate()
        {
            var buildInfo = Resources.Load<Core.BuildInfo>("BuildInfo");
            if (buildInfo != null && !string.IsNullOrEmpty(buildInfo.BuildDate))
            {
                return buildInfo.BuildDate;
            }

            return System.DateTime.Now.ToString("yyyy-MM-dd");
        }
    }
}
